include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

analyzer:
  exclude:
    # Build
    - "build/**"
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    - "coverage/**"
    # Assets
    - "assets/**"
    # Flutter Version Manager
    - ".fvm/**"
    # Tools
    #- "tool/**"
    - "scripts/**"
    - ".dart_tool/**"
    # Platform
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"
    # Code Generation
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    # Deprecated excluded files
    - "packages/deprecated/**"
    # Rust
    - "lib/src/ffi/**.dart"

  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  #enable-experiment:
  #  - dart2wasm

  errors:
    # Allow having TODOs in the code
    implicit_call_tearoffs: ignore
    todo: ignore
    curly_braces_in_flow_control_structures: ignore

    # Info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    missing_return: warning
    missing_required_param: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    # Public packages
    #public_member_api_docs: true
    #lines_longer_than_80_chars: true

    # Enabling rules
    always_use_package_imports: true
    avoid_relative_lib_imports: true

    # Disable rules
    implicit_call_tearoffs: false
    sort_pub_dependencies: false
    prefer_relative_imports: false
    prefer_final_locals: false
    avoid_escaping_inner_quotes: false
    curly_braces_in_flow_control_structures: false
    one_member_abstracts: false
