name: core
description: "A new Flutter FFI plugin project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1

resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffi: ^2.1.3
  ffigen: ^13.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
